code --install-extension adamgirton.gloom
code --install-extension akamud.vscode-theme-onedark
code --install-extension angryobject.react-pure-to-class-vscode
code --install-extension asvetliakov.snapshot-tools
code --install-extension dbaeumer.vscode-eslint
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension mauve.terraform
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.powershell
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension waderyan.gitblame
